name: Bug Report
description: Report a bug in Mouse Locomotor Tracker
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Load video with '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Messages
      description: Any error messages or stack traces.
      render: shell
      placeholder: Paste error messages here...

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Windows
        - Docker
    validations:
      required: true

  - type: dropdown
    id: python
    attributes:
      label: Python Version
      description: What Python version are you using?
      options:
        - "3.12"
        - "3.11"
        - "3.10"
        - "3.9"
    validations:
      required: true

  - type: input
    id: mlt-version
    attributes:
      label: MLT Version
      description: What version of Mouse Locomotor Tracker?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: video-info
    attributes:
      label: Video Information
      description: Details about the video being processed (optional).
      placeholder: |
        - Format: MP4
        - Resolution: 1920x1080
        - FPS: 30
        - Duration: 60s

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or files.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using a supported version
          required: true
