name: Feature Request
description: Suggest an idea for Mouse Locomotor Tracker
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature suggestion!
        Please provide detailed information to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature affect?
      options:
        - Tracking (detection, algorithms)
        - Analysis (metrics, calculations)
        - Visualization (plots, overlays)
        - Export (formats, data)
        - CLI (commands, interface)
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical / Blocking
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help.
      placeholder: |
        In my research, I need to...
        This feature would help by...

  - type: textarea
    id: example
    attributes:
      label: Example
      description: If possible, provide an example of how this feature would work.
      placeholder: |
        ```python
        # Example code or CLI command
        mlt analyze --new-feature video.mp4
        ```

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references.
